pub enum OpCode {
    Cls,
    Ret,
    Jp {addr: u16},
    Call {addr: u16},
    SE_vx_byte {x: u8, kk: u8},
    SNE_vx_byte {x: u8, kk: u8},
    SE_vx_vy {x: u8, y: u8},
    LD_vx_byte {x: u8, kk: u8},
    ADD_vx_byte {x: u8, kk: u8},
    LD_vx_vy {x: u8, y: u8},
    OR_vx_vy {x: u8, y: u8},
    AND_vx_vy {x: u8, y: u8},
    XOR_vx_vy {x: u8, y: u8},
    ADD_vx_vy {x: u8, y: u8},
    SUB_vx_vy {x: u8, y: u8},
    SHR_vx_vy {x: u8, y: u8},
    SUBN_vx_vy {x: u8, y: u8},
    SHL_vx_vy {x: u8, y: u8},
    SNE_vx_vy {x: u8, y: u8},
    LD_I_addr {addr: u16},
    JP_v0_addr {addr: u16},
    RND_vx_byte {x: u8, kk: u8},
    DRW_x_y_nibble {x: u8, y: u8, n: u8},
    SKP_vx {x: u8},
    SKNP_vx {x: u8},
    LD_vx_dt {x: u8},
    LD_vx_k {x: u8},
    LD_dt_vx {x: u8},
    LD_st_vx {x: u8},
    ADD_I_vx {x: u8},
    LD_F_vx {x: u8},
    LD_B_vx {x: u8},
    LD_I_vx {x: u8},
    LD_vx_I {x: u8},
}

